#!/bin/sh
####  PBS preamble

# Job Specifications
#PBS -N jam_mcsync

# Log-in Specifications
#PBS -M jmeluso@umich.edu
#PBS -m abe

# Processing Specifications:
#PBS -l nodes=1:ppn=4,pmem=4000mb,walltime=02:00:00
#PBS -j oe
#PBS -V

# Flux Allocation Specifications
#PBS -A engin_flux
#PBS -q flux
#PBS -l qos=flux

####  End PBS preamble

# Track execution outputs
if [ "x${PBS_NODEFILE}" != "x" ] ; then
   cat $PBS_NODEFILE   # contains a list of the CPUs you were using if run with PBS
fi

# Change to the scripts directory
cd /home/jmeluso/research_miscomm_est_def/scripts

# Use python to run with 20 cores
python test_mc_sync.py